apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-pods
subjects:
- kind: ServiceAccount
  name: readonly 
  apiGroup: ""
roleRef:
  kind: Role 
  name: readonly-role 
  apiGroup: rbac.authorization.k8s.io