apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: admin-role 
  apiGroup: ""
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: frontends
subjects:
- kind: ServiceAccount
  name: admin-role 
  apiGroup: ""
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: kube-node-lease
subjects:
- kind: ServiceAccount
  name: admin-role 
  apiGroup: ""
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: kube-public
subjects:
- kind: ServiceAccount
  name: admin-role 
  apiGroup: ""
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: admin-role 
  apiGroup: ""
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io